language: android
dist : xenial
sudo: required
jdk:  oraclejdk8
variables:
ANDROID_COMPILE_SDK: "28"
ANDROID_BUILD_TOOLS: "28.0.2"
ANDROID_SDK_TOOLS: "4333796"
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-26
    - extra-android-support
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
    - chmod +x ./gradlew
    - yes | android-sdk-linux/tools/bin/sdkmanager --licenses   
Build:    
script:  
    - ./gradlew assembleDebug
artifacts:
  paths:
    - app/build/outputs/ 
deploy:
  - provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: app/build/outputs/apk/release/*
    file_glob: true
    skip_cleanup: true
    on:
        branch: master  

