version: 2
orbs:
  aws-s3: circleci/aws-s3@1.1.0
  aws-cli: circleci/aws-cli@1.3.0 
  aws-code-deploy: circleci/aws-code-deploy@0.0.11
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug APK 
          command: ./gradlew assembleDebug
      - store_artifacts: # storing artifact  
          path: app/build/outputs/apk/
          destination: apks/
          # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
  deploy:
    machine:
      image: ubuntu-1604:201903-01 
    enabled: true
    working_directory: ~/code
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync s3://covidcare-artifact'  
workflows: # Define a Workflow running the build job, then the deploy job
    version:  2
    build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master # Only deploys when the commit is on the Master branch  
