version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.6
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug APK 
          command: ./gradlew assembleDebug
      - store_artifacts: # storing artifact  
          path: app/build/outputs/apk/
          destination: apks/
          # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
  deploy:
     docker: # Specify executor for running deploy job
       - image: 'circleci/node' # Specify docker image to use
     steps:
       - checkout
       - aws-s3/sync:
           from: .
           to: 's3://covidcare-artifact/'
           aws-access-key-id:  AWS_ACCESS_KEY_ID  
           aws-secret-access-key:    
           arguments: | # Optional arguments
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true # default is false
workflows: # Define a Workflow running the build job, then the deploy job
    version:  2
    build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master # Only deploys when the commit is on the Master branch  